dataset_path: sghosts/cf_gsm8k_6.5k_train
dataset_split: train
output_dir: out/vae/ckpts/hidden-vae-bigcos

vae_type: residual_mlp
hidden_size: 1024
latent_size: 256
intermediate_size: 512
device: cuda

tokens_per_epoch: # debug only.
token_seed: 0
response_only: true
validation_fraction: 0.1
split_seed: 0

lambda_mse: 1.0
lambda_cos: 0.5
lambda_norm: 0.0001
beta: 0.001
free_bits: 0.0

per_device_train_batch_size: 64000
per_device_eval_batch_size: 64000
num_train_epochs: 20 # overfit
learning_rate: 0.0001
eval_strategy: epoch
save_strategy: epoch
save_total_limit: 10
report_to: none
logging_steps: 1
