"""Extract chat-templated PROMPTS from the turkishdspark corpus for teacher-state collection.

The turkishdspark rows were generated by Qwen3.6-35B-A3B-FP8, so their completions are
off-distribution for our target (Qwen3.5-27B). We keep only the prompt prefix -- the span
before the first `loss_mask == 1` -- and let `collect_teacher_states.py` generate the
continuation with the real target. The prefix is already chat-templated, and Qwen3.5's
template with `enable_thinking=False` is byte-identical to the one that produced it, so it
is replayed verbatim via `format_name: pretemplated`.

  python scripts/build_turkish_prompts.py --out bench_data_tr
"""
from __future__ import annotations

import argparse
import json
import os
import random

SRC_DIR = "/root/turkishdspark/data/corpus"

# rows to emit per source: train mix, then a disjoint holdout.
# Sized so the collected mix lands near the English v2 mix5 token count (~4.9M tokens),
# NOT its row count -- Turkish prompts here are 2-5x longer than the English ones.
PLAN = {
    "tr-instructurca":         dict(train=24000, holdout=150, max_prompt=1024),
    "tr-function-calling-20k": dict(train=3000, holdout=50,  max_prompt=1024),
    "tr-multiturn":            dict(train=1200, holdout=50,  max_prompt=1536),
    "tr-tool-calling-10k":     dict(train=900,  holdout=50,  max_prompt=1536),
}


def prompt_prefix(row: dict) -> tuple[list[int], int] | None:
    ids, lm = row["input_ids"], row["loss_mask"]
    if not ids or not lm or 1 not in lm:
        return None
    k = lm.index(1)
    return ids[:k], k


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="bench_data_tr")
    ap.add_argument("--tokenizer", default="Qwen/Qwen3.5-27B")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    from transformers import AutoTokenizer

    tok = AutoTokenizer.from_pretrained(args.tokenizer)
    os.makedirs(args.out, exist_ok=True)
    rng = random.Random(args.seed)

    for name, cfg in PLAN.items():
        path = os.path.join(SRC_DIR, f"{name}.jsonl")
        seen: set[str] = set()
        # group by primary_id: in tr-multiturn the `_gen0/_gen1/...` rows are successive
        # TURNS of one conversation with growing prompts, so they must stay together --
        # splitting them across train/holdout would leak the conversation.
        groups: dict[str, list[tuple[str, int]]] = {}
        with open(path) as fh:
            for line in fh:
                row = json.loads(line)
                got = prompt_prefix(row)
                if got is None:
                    continue
                ids, k = got
                if k > cfg["max_prompt"] or k < 16:
                    continue
                text = tok.decode(ids)
                if text in seen:  # dedupe on the prompt itself, not on the id
                    continue
                seen.add(text)
                groups.setdefault(row.get("primary_id") or row.get("id"), []).append((text, k))

        keys = sorted(groups)
        rng.shuffle(keys)

        holdout: list[tuple[str, int]] = []
        train: list[tuple[str, int]] = []
        for key in keys:
            bucket = holdout if len(holdout) < cfg["holdout"] else train
            bucket.extend(groups[key])
            if len(train) >= cfg["train"]:
                break
        train = train[: cfg["train"]]
        if len(train) < cfg["train"]:
            print(f"WARN {name}: only {len(train)} train rows, wanted {cfg['train']}")

        for split, rows in (("train", train), ("holdout", holdout)):
            outp = os.path.join(args.out, f"{name}.{split}.jsonl")
            with open(outp, "w") as fh:
                for text, k in rows:
                    fh.write(json.dumps({"prompt": text, "prompt_tokens": k},
                                        ensure_ascii=False) + "\n")
            ntok = sum(k for _, k in rows)
            mean = ntok / max(len(rows), 1)
            print(f"{outp:52s} rows={len(rows):5d} mean_prompt_tok={mean:7.1f}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
