"""Generate the Turkish-v2 teacher-state collection configs for 4B / 9B / 27B.

WHY THE THREE SIZES DIFFER
--------------------------
4B and 27B v1 both collected the SAME 29,100 rows out of `bench_data_tr/*.train.jsonl`.
`bench_data_tr_v2` was rebuilt with the same seed and larger per-source `train` counts, and the
builder fills HOLDOUT first from a seeded shuffle -- so the v2 files are a strict PREFIX EXTENSION
of the v1 files (verified byte-for-byte, holdouts identical). Their existing teacher states stay
valid and only the TAIL needs collecting.

9B v1 is the exception: it collected from `data/turkish_prompts/*.jsonl` (14,746 rows,
`format_name: raw_prompt`), a different and smaller prompt set. There is no prefix relationship,
so unifying 9B onto the same corpus means collecting all 56,699 rows. That is the price of making
the three sizes comparable; it was NOT comparable before.
"""
import json, os

# (source stem, v1 train rows already collected for 4B/27B, v2 train rows)
SRC = [
    ("tr-instructurca",         "tr_instruct",   24000, 39264),
    ("tr-function-calling-20k", "tr_funccall",    3000,  8000),
    ("tr-tool-calling-10k",     "tr_toolcall",     900,  7290),
    ("tr-multiturn",            "tr_multiturn",   1200,  2145),
]
# per-size batch sizes copied from the v1 configs that are known to fit
SIZES = {
    "4btr":  dict(model="Qwen/Qwen3.5-4B",  gen=64, hid=24, reuse=True),
    "9btr":  dict(model="Qwen/Qwen3.5-9B",  gen=48, hid=16, reuse=False),  # full recollect
    "tr27b": dict(model="Qwen/Qwen3.5-27B", gen=24, hid=12, reuse=True),
}
SHARD_ROWS = 4000            # keep a shard under ~2h so a crash costs little


def main() -> int:
    for size, cfg in SIZES.items():
        out = f"collect_configs/stage1_{size}_v2"
        os.makedirs(out, exist_ok=True)
        n = 0
        for stem, src, v1_end, v2_end in SRC:
            start = v1_end if cfg["reuse"] else 0
            if start >= v2_end:
                continue
            a = start
            while a < v2_end:
                b = min(a + SHARD_ROWS, v2_end)
                name = f"{src.replace('tr_','')}_{a}_{b}"
                with open(f"{out}/{name}.yaml", "w") as fh:
                    fh.write(
                        f"# Turkish v2, {cfg['model']}. Rows [{a},{b}) of "
                        f"bench_data_tr_v2/{stem}.train.jsonl.\n"
                        f"# Prompts are chat-templated PREFIXES; continuations are generated by the\n"
                        f"# REAL target (the corpus's own completions came from Qwen3.6-35B-A3B-FP8\n"
                        f"# and are discarded). enable_thinking=False is baked into the prompt text.\n"
                        f"model_id: {cfg['model']}\n"
                        f"dataset_name: json\n"
                        f"data_files: bench_data_tr_v2/{stem}.train.jsonl\n"
                        f"dataset_config: null\nsplit: train\n"
                        f"dataset_start: {a}\ndataset_end: {b}\n"
                        f"source: {src}\nformat_name: pretemplated\n"
                        f"generation_max_new_tokens: 256\n"
                        f"generation_batch_size: {cfg['gen']}\n"
                        f"hidden_batch_size: {cfg['hid']}\n"
                        f"storage_dtype: float16\ndtype: float16\ndevice: cuda:0\n"
                        f"output_dir: teacher_states/stage1-{size}-v2-{name}\n")
                n += b - a
                a = b
        print(f"{out:38s} shards={len(os.listdir(out)):3d}  rows={n:6d}"
              f"  ({'tail only' if cfg['reuse'] else 'FULL recollect'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
