"""Generate teacher-state collect configs for the German/French drafter run.

Mirrors ``gen_tr_v2_configs.py``: one YAML per [start,end) shard of one source file, so a shard
can be re-run without redoing its neighbours.

BATCH SIZES ARE SIZED FROM FREE VRAM, NOT CARD VRAM. This box is shared -- at the time of writing
another user's training job holds 74-93 GB on every card -- so the usual "assume a ~97 GB card"
sizing would OOM us and, worse, could OOM the neighbour. ``--free-gb`` is the budget we are
willing to occupy on ONE card; everything is derived from it, and the defaults are deliberately
timid. Measure with a smoke probe before trusting a larger value.

  python scripts/gen_multilingual_configs.py --lang de --free-gb 18
"""
from __future__ import annotations

import argparse
import glob
import json
import os

WEIGHTS_GB = 8.6          # Qwen3.5-4B fp16 + CUDA context
GEN_GB_PER_SEQ = 0.055    # KV cache for a ~1.5k-token window at 4B
HID_GB_PER_SEQ = 1.66     # output_hidden_states=True, measured during the Turkish run


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lang", required=True, choices=("de", "fr"))
    ap.add_argument("--data-dir", default=None)
    ap.add_argument("--out-dir", default=None)
    ap.add_argument("--model", default="Qwen/Qwen3.5-4B")
    ap.add_argument("--shard", type=int, default=2000, help="rows per shard")
    ap.add_argument("--free-gb", type=float, default=18.0,
                    help="VRAM we may occupy on ONE card, total, including weights")
    ap.add_argument("--max-new", type=int, default=256)
    args = ap.parse_args()

    data_dir = args.data_dir or f"bench_data_{args.lang}"
    out_dir = args.out_dir or f"collect_configs/stage1_{args.lang}"
    os.makedirs(out_dir, exist_ok=True)

    budget = args.free_gb - WEIGHTS_GB
    if budget <= 2:
        raise SystemExit(f"--free-gb {args.free_gb} leaves {budget:.1f} GB after weights; too tight")
    # Phase 1 (generate) and phase 2 (hidden states) run at different batch sizes; each gets the
    # whole budget in turn, so size them independently rather than splitting it.
    gen_bs = max(4, int(budget / GEN_GB_PER_SEQ / 2))     # /2: leave room for logits + activations
    hid_bs = max(1, int(budget / HID_GB_PER_SEQ))
    print(f"  budget {budget:.1f} GB after weights -> generation_batch_size={gen_bs} "
          f"hidden_batch_size={hid_bs}")

    n = 0
    for path in sorted(glob.glob(os.path.join(data_dir, "*.train.jsonl"))):
        base = os.path.basename(path).replace(".train.jsonl", "")
        rows = sum(1 for _ in open(path))
        src = base.replace("-", "_")
        for start in range(0, rows, args.shard):
            end = min(start + args.shard, rows)
            name = f"{base}_{start}_{end}.yaml"
            body = f"""# {args.lang.upper()} drafter data, {args.model}. Rows [{start},{end}) of {path}.
# Prompts are chat-templated PREFIXES; the continuation is generated by the REAL target -- the
# corpora's own completions came from other models and are discarded. enable_thinking=False is
# baked into the prompt text (see build_multilingual_prompts.py).
# Batch sizes are sized for a SHARED card, see gen_multilingual_configs.py --free-gb.
model_id: {args.model}
dataset_name: json
data_files: {path}
dataset_config: null
split: train
dataset_start: {start}
dataset_end: {end}
source: {src}
format_name: pretemplated
generation_max_new_tokens: {args.max_new}
generation_batch_size: {gen_bs}
hidden_batch_size: {hid_bs}
storage_dtype: float16
dtype: float16
device: cuda:0
output_dir: teacher_states/stage1-{args.lang}-{base}_{start}_{end}
"""
            open(os.path.join(out_dir, name), "w").write(body)
            n += 1
    print(f"  wrote {n} configs to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
